package org.frc.team5409.churro;

import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj.TimedRobot;

import org.frc.team5409.churro.subsystems.*;
import org.frc.team5409.churro.commands.*;
import org.frc.team5409.churro.control.ServiceManager;



public class Robot extends TimedRobot {
    private RobotContainer m_robotContainer;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static TurretControl turretControl;
    public static NavX navX;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static double     c_defaultHertz = 200;//Hz

    public static OI         oi;

    public Robot() {
        m_period = 1.0d / c_defaultHertz;
    }


    @Override
    public void robotInit() {
        m_robotContainer = new RobotContainer();

        turretControl = new TurretControl();
        navX = new NavX();

        oi = new OI();

        ServiceManager.getInstance().startServices();
    }

    @Override
    public void disabledInit(){
        ServiceManager.getInstance().stopServices();
    }

    @Override
    public void disabledPeriodic() {
        CommandScheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
        
    }

    @Override
    public void autonomousPeriodic() {
        CommandScheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
        
    }

    @Override
    public void teleopPeriodic() {
        CommandScheduler.getInstance().run();
    }
}
