// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5409.testtt.subsystems;


import org.usfirst.frc5409.testtt.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class drivetrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_VictorSPX s_E4t_360_left_QuadratureEncoder;
    private WPI_VictorSPX s_E4t_360_right_QuadratureEncoder;
    private RobotDrive robotDrive21;
    private Encoder m_rightDrive_VictorSPX_C20;
    private Encoder m_leftDrive_VictorSPX_C20;
    private AnalogInput analogInput1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        s_E4t_360_left_QuadratureEncoder = new WPI_VictorSPX(20);
        
        
        
        s_E4t_360_right_QuadratureEncoder = new WPI_VictorSPX(21);
        
        
        
        robotDrive21 = new RobotDrive(s_E4t_360_left_QuadratureEncoder, s_E4t_360_right_QuadratureEncoder);
        
        robotDrive21.setSafetyEnabled(true);
        robotDrive21.setExpiration(0.1);
        robotDrive21.setSensitivity(0.5);
        robotDrive21.setMaxOutput(1.0);

        
        m_rightDrive_VictorSPX_C20 = new Encoder(2, 3, false, EncodingType.k4X);
        addChild("m_rightDrive_Victor SPX_C20",m_rightDrive_VictorSPX_C20);
        m_rightDrive_VictorSPX_C20.setDistancePerPulse(1.0);
        m_rightDrive_VictorSPX_C20.setPIDSourceType(PIDSourceType.kRate);
        
        m_leftDrive_VictorSPX_C20 = new Encoder(4, 5, false, EncodingType.k4X);
        addChild("m_leftDrive_Victor SPX_C20",m_leftDrive_VictorSPX_C20);
        m_leftDrive_VictorSPX_C20.setDistancePerPulse(1.0);
        m_leftDrive_VictorSPX_C20.setPIDSourceType(PIDSourceType.kRate);
        
        analogInput1 = new AnalogInput(0);
        addChild("Analog Input 1 ",analogInput1);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Arcadedrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

