package org.usfirst.frc5409.Testrobot.subsystems;

import org.usfirst.frc5409.Testrobot.commands.*;
import org.usfirst.frc5409.Testrobot.util.Range;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drivetrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_VictorSPX m_leftDrive_Victor_SPX_C20;
    private WPI_VictorSPX m_rightDrive_Victor_SPX_C21;
    private DifferentialDrive differentialDrive;
    private Encoder m_E4t_360_left_Quad_Encoder;
    private Encoder m_E4t_360_right_Quad_Encoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double c_Drivetrain_Wheel_Diamater_in = 6;
    public static final double c_Drivetrain_Gear_Ratio = 10.71;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    public static final double c_Distance_Per_Pulse = 
        (Math.PI * c_Drivetrain_Wheel_Diamater_in) / (c_Drivetrain_Gear_Ratio*4);

    public static final Range<Double> c_Drivetrain_velocity_range_in =
        new Range(-39.97*5, 39.75*5);

    private PIDController pid_leftDrive_velocity;
    private PIDController pid_rightDrive_velocity;

    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        m_leftDrive_Victor_SPX_C20 = new WPI_VictorSPX(20);
        
        
        
        m_rightDrive_Victor_SPX_C21 = new WPI_VictorSPX(21);
        
        
        
        differentialDrive = new DifferentialDrive(m_leftDrive_Victor_SPX_C20, m_rightDrive_Victor_SPX_C21);
        addChild("Differential Drive",differentialDrive);
        differentialDrive.setSafetyEnabled(true);
        differentialDrive.setExpiration(0.1);
        differentialDrive.setMaxOutput(1.0);

        
        m_E4t_360_left_Quad_Encoder = new Encoder(0, 1, false, EncodingType.k4X);
        addChild("m_E4t_360_left_Quad_Encoder",m_E4t_360_left_Quad_Encoder);
        m_E4t_360_left_Quad_Encoder.setDistancePerPulse(1.0);
        m_E4t_360_left_Quad_Encoder.setPIDSourceType(PIDSourceType.kRate);
        
        m_E4t_360_right_Quad_Encoder = new Encoder(2, 3, false, EncodingType.k4X);
        addChild("m_E4t_360_right_Quad_Encoder",m_E4t_360_right_Quad_Encoder);
        m_E4t_360_right_Quad_Encoder.setDistancePerPulse(1.0);
        m_E4t_360_right_Quad_Encoder.setPIDSourceType(PIDSourceType.kRate);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        m_E4t_360_left_Quad_Encoder.setDistancePerPulse(c_Distance_Per_Pulse);
        m_E4t_360_right_Quad_Encoder.setDistancePerPulse(c_Distance_Per_Pulse);
              
        pid_leftDrive_velocity = new PIDController(
            1,
            0,
            0,
            m_E4t_360_left_Quad_Encoder,
            m_leftDrive_Victor_SPX_C20
        );
        pid_leftDrive_velocity.setContinuous(false);
        pid_leftDrive_velocity.setOutputRange(-1, 1);
        pid_leftDrive_velocity.setInputRange(c_Drivetrain_velocity_range_in.min,
                                             c_Drivetrain_velocity_range_in.max);
                                             
        pid_leftDrive_velocity.enable();

        pid_rightDrive_velocity = new PIDController(
            1,
            0,
            0,
            m_E4t_360_left_Quad_Encoder,
            m_leftDrive_Victor_SPX_C20
        );
        pid_rightDrive_velocity.setContinuous(false);
        pid_rightDrive_velocity.setOutputRange(-1, 1);  
        pid_rightDrive_velocity.setInputRange(c_Drivetrain_velocity_range_in.min,
                                             c_Drivetrain_velocity_range_in.max);
        pid_rightDrive_velocity.enable();
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
        setDefaultCommand(new Drive());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        SmartDashboard.putNumber("Encoder left",
            m_E4t_360_left_Quad_Encoder.getDistance());

        SmartDashboard.putNumber("Encoder right",
            m_E4t_360_right_Quad_Encoder.getDistance());
        
        m_leftDrive_Victor_SPX_C20.set(pid_leftDrive_velocity.get());
        m_rightDrive_Victor_SPX_C21.set(pid_rightDrive_velocity.get());
        
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    public void setVelocity(double left_velocity, double right_velocity) {
        pid_leftDrive_velocity.setSetpoint(left_velocity);
        pid_leftDrive_velocity.setSetpoint(right_velocity);
    }


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

