package org.usfirst.frc5409.Testrobot.subsystems;

import org.usfirst.frc5409.Testrobot.subsystems.limelight.ll.*;
import edu.wpi.first.wpilibj.command.Subsystem;

import org.usfirst.frc5409.Testrobot.commands.*;
import edu.wpi.first.networktables.*;

public class Limelight extends Subsystem {
    private NetworkTable      m_limelight_data;
    private NetworkTableEntry m_data_entry_led_mode;
    private NetworkTableEntry m_data_entry_cam_mode;
    private NetworkTableEntry m_data_entry_pipeline;

    public Limelight() {
        // Might need to wait for table creation, maybe add a listener for the table
        m_limelight_data = NetworkTableInstance.getDefault().getTable("limelight");

        m_data_entry_led_mode = m_limelight_data.getEntry("ledMode");
        m_data_entry_cam_mode = m_limelight_data.getEntry("camMode");
        m_data_entry_pipeline = m_limelight_data.getEntry("pipeline");

        // Maybe create a watchdog system in case of limelight malfunction (i.e disconnection)
    }
    
    @Override
    public void initDefaultCommand() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Drive());
    }
    
    @Override
    public void periodic() {

    }

    public void setCameraMode(CameraModA)

}